In [2]:
import torch

In [4]:
# requires_grad=True >> This sets up computational tracking on the tensor.
x = torch.tensor(2.0, requires_grad=True) 

In [5]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [6]:
# Backpropagation
y.backward()

In [7]:
print(x.grad) # Gradient of y = 63 at x = 2

tensor(93.)


## Multistep Backward propagation

In [8]:
x = torch.tensor([[1.,2,3],[3,2,1]], requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [9]:
# First Layer
y = 3*x + 2
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [10]:
# Second Layer
z = 2*y**2
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [11]:
# Output
out = z.mean()
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [12]:
# Backprop
out.backward()
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])


### There is a gradient for each x value